blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/dcondrey/zotero-validate/discussions
    about: Ask questions and discuss in GitHub Discussions
